#!/usr/bin/env bash
# Build + publish a release: wasm client -> box, paks -> R2.
#
# Prereqs:
#   - emsdk activated, gl4es built (see top-level README build steps)
#   - rclone configured with an R2 remote (see deploy/rclone.conf.example)
#   - SSH access to the box as etweb@<BOX_IP>
#
# Env (override as needed):
#   BOX_IP        target box for the shell + game server          (required)
#   R2_REMOTE     rclone remote:bucket for paks   (default r2:et-assets)
#   ASSET_BASE    public base URL of the paks     (default https://assets.et.helja.la)
#   WS_URL        grey-cloud socket host          (default wss://net.et.helja.la/)
#   GAME_SERVER   engine-side connect token       (default 127.0.0.1:27960)
#   SKIP_BUILD=1  reuse the existing build/web
#
# Usage: BOX_IP=1.2.3.4 deploy/release.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

: "${BOX_IP:?set BOX_IP=<hetzner ip>}"
R2_REMOTE="${R2_REMOTE:-r2:et-assets}"
ASSET_BASE="${ASSET_BASE:-https://assets.et.helja.la}"
WS_URL="${WS_URL:-wss://net.et.helja.la/}"
GAME_SERVER="${GAME_SERVER:-127.0.0.1:27960}"

# 1. build the wasm client (unless reusing)
if [ "${SKIP_BUILD:-0}" != "1" ]; then
  echo "== building wasm client =="
  # shellcheck disable=SC1091
  source tools/emsdk/emsdk_env.sh >/dev/null 2>&1 || true
  cmake --build build/web -j"$(getconf _NPROCESSORS_ONLN)" --target etl
fi

# 2. stage with the production asset base baked into manifest.json
echo "== staging (assets -> $ASSET_BASE) =="
ASSET_BASE="$ASSET_BASE" ./scripts/stage-web.sh >/dev/null

# 3. generate the production config.js to a temp file (the committed
#    web/config.js keeps its local-dev defaults; not clobbered)
PROD_CONFIG="$(mktemp)"
trap 'rm -f "$PROD_CONFIG"' EXIT
cat > "$PROD_CONFIG" <<EOF
// generated by deploy/release.sh
window.ET_CONFIG = {
  server: '${GAME_SERVER}',
  wsUrl: '${WS_URL}',
  assetBase: '${ASSET_BASE}/',
  downloadSize: '~230 MB',
};
EOF

# 4. paks + loose mod wasm -> R2 (zero egress on the way back out).
#    -L resolves the symlinks stage-web.sh created.
echo "== syncing paks to $R2_REMOTE =="
rclone sync -L --transfers 4 --s3-no-check-bucket \
  web/files/ "$R2_REMOTE/"

# 5. shell + manifest -> the box (tiny; -L resolves etl.js/wasm symlinks)
echo "== shipping shell to $BOX_IP =="
rsync -avL \
  web/index.html web/boot.js web/etl.js web/etl.wasm web/manifest.json \
  "etweb@${BOX_IP}:/opt/et-web/web/"
rsync -av "$PROD_CONFIG" "etweb@${BOX_IP}:/opt/et-web/web/config.js"

echo
echo "released. open https://et.helja.la (hard-refresh; manifest is no-cache)"
echo "if you set long browser TTLs, purge the CF cache for et.helja.la/manifest.json + /etl.js"
