#!/usr/bin/env bash
# Build + publish a release: wasm client -> box, paks -> R2.
#
# Generic + parameterized: all deployment specifics come from env (a private
# wrapper - e.g. helja.la via `chamber exec` - supplies them). Nothing here is
# host-specific; placeholders below are illustrative only.
#
# Prereqs:
#   - emsdk activated, gl4es built (see top-level README build steps)
#   - rclone reachable, R2 creds in env (RCLONE_CONFIG_R2_* - see
#     deploy/rclone.conf.example); never written to disk
#   - SSH to the box as etweb@<SSH_TARGET> (a Tailscale hostname, a normal
#     SSH host alias, or an IP)
#
# Env:
#   SSH_TARGET    box host for the shell + game server (Tailscale name / host / IP)  (required)
#   BOX_IP        deprecated alias for SSH_TARGET                                (optional)
#   ASSET_BASE    public base URL of the paks (e.g. https://assets.example.com)  (required)
#   R2_REMOTE     rclone remote:bucket for paks (e.g. r2:et-assets)              (required)
#   WS_URL        socket override; EMPTY -> same-origin wss://<host>/net default (optional)
#   GAME_SERVER   engine-side connect token       (default 127.0.0.1:27960)
#   SKIP_BUILD=1  reuse the existing build/web
#
# Convenience: a gitignored deploy/deploy.env is sourced if present.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# shellcheck disable=SC1091
[ -f deploy/deploy.env ] && . deploy/deploy.env

SSH_TARGET="${SSH_TARGET:-${BOX_IP:-}}"
: "${SSH_TARGET:?set SSH_TARGET=<box host: tailscale name, ssh alias, or ip>}"
: "${ASSET_BASE:?set ASSET_BASE=<public pak base url>}"
: "${R2_REMOTE:?set R2_REMOTE=<rclone remote:bucket>}"
WS_URL="${WS_URL:-}"               # empty -> engine same-origin default
GAME_SERVER="${GAME_SERVER:-127.0.0.1:27960}"
ASSET_BASE="${ASSET_BASE%/}"       # normalize (we add the slash)

# 1. build the wasm client + game modules (unless reusing). Build ALL targets,
#    not just etl: the legacy_*.pk3 (cgame/ui) we ship to R2 + the server must
#    be rebuilt too when the mod changes, else a stale pk3 goes out.
if [ "${SKIP_BUILD:-0}" != "1" ]; then
  echo "== building wasm client + mods =="
  # shellcheck disable=SC1091
  source tools/emsdk/emsdk_env.sh >/dev/null 2>&1 || true
  cmake --build build/web -j"$(getconf _NPROCESSORS_ONLN)"
fi

# 2. stage with the production asset base baked into manifest.json
echo "== staging (assets -> $ASSET_BASE) =="
ASSET_BASE="$ASSET_BASE" ./scripts/stage-web.sh >/dev/null

# 3. generate the production config.js to a temp file (the committed
#    web/config.js keeps its local-dev defaults; not clobbered)
PROD_CONFIG="$(mktemp)"
trap 'rm -f "$PROD_CONFIG"' EXIT
cat > "$PROD_CONFIG" <<EOF
// generated by deploy/release.sh
window.ET_CONFIG = {
  server: '${GAME_SERVER}',
  wsUrl: '${WS_URL}',
  assetBase: '${ASSET_BASE}/',
  downloadSize: '~230 MB',
};
EOF

# 4. paks + loose mod wasm -> R2 (zero egress on the way back out).
#    -L resolves the symlinks stage-web.sh created.
echo "== syncing paks to $R2_REMOTE =="
rclone sync -L --transfers 4 --s3-no-check-bucket \
  web/files/ "$R2_REMOTE/"

# 5. shell + manifest -> the box (tiny; -L resolves etl.js/wasm symlinks)
echo "== shipping shell to $SSH_TARGET =="
rsync -avL \
  web/index.html web/boot.js web/etl.js web/etl.wasm web/manifest.json \
  "etweb@${SSH_TARGET}:/opt/et-web/web/"
rsync -av "$PROD_CONFIG" "etweb@${SSH_TARGET}:/opt/et-web/web/config.js"

# 6. legacy mod pk3 -> the server's mod dir. This is the SAME artifact uploaded
#    to R2 in step 4, so the server and the browser clients run a byte-identical
#    mod (the native build's qagame.so, installed by box-setup, is from the same
#    commit). Restart etlded only when the pk3 actually changed, so shell-only
#    releases don't kick connected players. (box-setup leaves etlded enabled but
#    not started; the first release here is what brings it up.)
echo "== shipping legacy mod pk3 to $SSH_TARGET =="
if rsync -aLi web/files/legacy/legacy_*.pk3 \
     "etweb@${SSH_TARGET}:/opt/et-web/server/legacy/" | grep -q 'legacy_'; then
  echo "   mod pk3 changed -> (re)starting etlded"
  ssh "root@${SSH_TARGET}" systemctl restart etlded
else
  echo "   mod pk3 unchanged -> leaving etlded as-is"
fi

echo
echo "released. hard-refresh the site (manifest + etl.js are no-cache)."
echo "if you set long browser TTLs, purge the CDN cache for /manifest.json + /etl.js"
